import { BookOpen, Cat, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, Fish, Headphones, Mic, Pause, PawPrint, Play, Sparkles, Volume2 } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { AppShell } from './components/layout/AppShell';
import { Button } from './components/ui/Button';
import { Surface } from './components/ui/Surface';
type Episode={id:string;level:number;series_title:string;episode_number:number;title:string;local_video_filename:string;is_published:boolean;is_learned:boolean};type Sentence={id:string;english:string;chinese:string;is_featured:boolean};type Vocab={id:string;word:string;phonetic:string;meaning:string};type Knowledge={id:string;title:string;explanation:string;examples:string[]};type PastTensePair={base:string;past:string;meaning:string};type Detail=Episode&{chinese_title:string;story_summary:string;story_theme:string;sentences:Sentence[];vocab:Vocab[];knowledge:Knowledge[];comprehension_questions:string[];retell_steps:string[];past_tense_pairs:PastTensePair[]};type Stats={learned_episodes:number;total_words:number;practice_count:number;mistake_count:number};type Result={attempt_id:string;is_correct:boolean;message:string;similarity?:number};type View='home'|'episode'|'dictation'|'speaking'|'login';
type BrowserRecognition={lang:string;interimResults:boolean;onresult:((event:{results:ArrayLike<ArrayLike<{transcript:string}>>})=>void)|null;start:()=>void;stop:()=>void};type BrowserRecognitionConstructor=new()=>BrowserRecognition;
const base=import.meta.env.VITE_API_BASE_URL??'http://localhost:8000';async function api<T>(path:string,init?:RequestInit):Promise<T>{const r=await fetch(`${base}/api/v1${path}`,{headers:{'Content-Type':'application/json',...init?.headers},...init});if(!r.ok)throw new Error('暂不可用');return r.json() as Promise<T>;}function speak(text:string){const synthesis=window.speechSynthesis;if(!synthesis||typeof window.SpeechSynthesisUtterance!=='function')return false;const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.82;synthesis.cancel();synthesis.speak(u);return true;}
export function App(){const[view,setView]=useState<View>('home');const[episodes,setEpisodes]=useState<Episode[]>([]);const[stats,setStats]=useState<Stats>({learned_episodes:0,total_words:0,practice_count:0,mistake_count:0});const[episode,setEpisode]=useState<Detail|null>(null);const[error,setError]=useState('');const[profile,setProfile]=useState('小咪');useEffect(()=>{let alive=true;void(async()=>{try{const list=await api<{items:Episode[]}>('/episodes');const current=await api<Stats>('/stats');if(alive){setEpisodes(list.items);setStats(current);}}catch{if(alive)setError('小鱼干暂时迷路啦，稍后再试一次。');}})();return()=>{alive=false;};},[]);async function open(id:string,target:View='episode'){try{setEpisode(await api<Detail>(`/episodes/${id}`));setView(target);setError('');}catch{setError('这一集还没准备好，请稍后再试。');}}async function refresh(){setStats(await api<Stats>('/stats'));}return <AppShell>{view==='home'?<Home episodes={episodes} stats={stats} error={error} profile={profile} open={open} login={()=>setView('login')}/>:view==='login'?<Login done={name=>{setProfile(name);setView('home');}}/>:episode?<Learning view={view} episode={episode} back={()=>setView('home')} change={setView} refresh={refresh}/>:null}</AppShell>;}
function Home({episodes,stats,error,profile,open,login}:{episodes:Episode[];stats:Stats;error:string;profile:string;open:(id:string,target?:View)=>void;login:()=>void}){
  const[level,setLevel]=useState(1);const[series,setSeries]=useState('');const[section,setSection]=useState<'today'|'bookshelf'|'progress'>('today');const today=episodes.find(item=>!item.is_learned)??episodes[0];
  return <div className="page-stack home">
    <section className="welcome-panel home-welcome"><div><p className="eyebrow"><Sparkles size={18}/> 嗨，{profile}</p><h2>今天继续学习</h2><p>凑凑喵已经把今天的任务排好啦。</p></div><div className="mascot" aria-label="凑凑喵"><Cat size={68}/><PawPrint className="mascot__paw" size={24}/></div><Button variant="secondary" onClick={login}>切换小伙伴</Button></section>
    <nav className="home-nav" aria-label="首页内容"><button className={section==='today'?'active':''} onClick={()=>setSection('today')}>今日学习</button><button className={section==='bookshelf'?'active':''} onClick={()=>setSection('bookshelf')}>剧集书架</button><button className={section==='progress'?'active':''} onClick={()=>setSection('progress')}>成长记录</button></nav>
    {section==='today'&&<div className="home-section">{today?<><Surface className="continue-card"><div><p className="eyebrow"><Fish size={18}/> 今天就学这一集</p><h2>Level {today.level} · {today.series_title}</h2><p>第 {today.episode_number} 集 · {today.title}</p><p>先看懂故事，再练单词，最后勇敢开口。</p></div><Button onClick={()=>open(today.id)}>继续学习</Button></Surface><section className="story-map"><div className="section-heading"><h2>三步完成今天的任务</h2><p>想从哪一步开始都可以。</p></div><div className="story-map__steps"><button onClick={()=>open(today.id,'episode')}><span>1</span><BookOpen size={24}/><strong>看故事</strong><small>台词、单词和句型</small></button><button onClick={()=>open(today.id,'dictation')}><span>2</span><Headphones size={24}/><strong>单词听写</strong><small>看中文或听发音</small></button><button onClick={()=>open(today.id,'speaking')}><span>3</span><Mic size={24}/><strong>句子跟读</strong><small>录音并检查发音</small></button></div></section></>:<Surface><h2>今天还没有学习任务</h2><p className="empty-state">请先到剧集书架看看已经整理好的内容。</p><Button onClick={()=>setSection('bookshelf')}>打开剧集书架</Button></Surface>}</div>}
    {section==='bookshelf'&&<section className="home-section"><div className="section-heading"><h2>动画学习小书架</h2><p>先选 Level，再选剧集，最后开始其中的一集。</p></div><div className="level-list">{Array.from({length:9},(_,i)=>i+1).map(n=>{const items=episodes.filter(item=>item.level===n);const seriesTitles=[...new Set(items.map(item=>item.series_title))];return <div className="level-card" key={n}><button className="level-card__button" onClick={()=>{setLevel(level===n?0:n);setSeries('');}} aria-expanded={level===n}><span>Level {n}</span><span>{items.length?`${items.length} 集已发布`:'等待整理'}<ChevronDown size={20}/></span></button>{level===n&&<div className="level-card__content">{items.length?<div className="series-list">{seriesTitles.map(seriesTitle=>{const seriesEpisodes=items.filter(item=>item.series_title===seriesTitle).sort((a,b)=>a.episode_number-b.episode_number);return <div className="series-card" key={seriesTitle}><button className="series-card__button" onClick={()=>setSeries(series===seriesTitle?'':seriesTitle)} aria-expanded={series===seriesTitle}><span>{seriesTitle}</span><span>{seriesEpisodes.length} 集 <ChevronDown size={18}/></span></button>{series===seriesTitle&&<div className="series-card__content">{seriesEpisodes.map(item=><div className="episode-row" key={item.id}><div><strong>第 {item.episode_number} 集 · {item.title}</strong><span>{item.is_learned?'已经学过，真棒！':'准备好一起开始啦'}</span></div><Button onClick={()=>open(item.id)}>开始学习</Button></div>)}</div>}</div>;})}</div>:<p className="empty-state">凑凑喵正在把这一层的小故事整理得清清楚楚。</p>}</div>}</div>;})}</div></section>}
    {section==='progress'&&<section className="home-section"><div className="section-heading"><h2>我的成长记录</h2><p>每次认真练习，都会留下一个小脚印。</p></div><div className="stat-grid">{[['已学剧集',stats.learned_episodes,'集'],['累计单词',stats.total_words,'个'],['练习次数',stats.practice_count,'次'],['需要复习',stats.mistake_count,'项']].map(([label,value,unit])=><Surface className="stat" key={label}><strong>{value}<small>{unit}</small></strong><span>{label}</span></Surface>)}</div></section>}
    {error&&<p className="gentle-note" role="status">{error}</p>}
  </div>;
}
function Login({done}:{done:(name:string)=>void}){const[email,setEmail]=useState('parent@example.com');const[msg,setMsg]=useState('');async function submit(e:React.FormEvent){e.preventDefault();try{const data=await api<{profile:{display_name:string}}>('/auth/login',{method:'POST',body:JSON.stringify({email})});setMsg('欢迎回来，凑凑喵已经准备好啦。');done(data.profile.display_name);}catch{setMsg('请检查邮箱后再试试。');}}return <Surface className="login-card"><p className="eyebrow"><Sparkles size={18}/> 家长登录</p><h2>把学习脚印带回来</h2><p>测试阶段使用家庭演示登录；接入 Supabase 后会自动替换为真实账户。</p><form onSubmit={submit}><label htmlFor="email">家长邮箱</label><input id="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><Button type="submit">进入乐园</Button></form>{msg&&<p className="gentle-note" role="status">{msg}</p>}</Surface>;}
function Learning({view,episode,back,change,refresh}:{view:View;episode:Detail;back:()=>void;change:(v:View)=>void;refresh:()=>Promise<void>}){const[finished,setFinished]=useState(false);async function complete(){await api(`/episodes/${episode.id}/learned`,{method:'POST'});await refresh();setFinished(true);}return <div className="page-stack"><button className="back-link" onClick={back}><ChevronLeft size={20}/> 回到小书架</button><div className="episode-heading"><p className="eyebrow">Level {episode.level} · {episode.series_title} · 第 {episode.episode_number} 集</p><h2>{episode.title}</h2><p className="video-cue"><BookOpen size={20}/><span>请在本地打开对应视频观看</span>：<strong>{episode.local_video_filename}</strong></p></div><nav className="learning-nav" aria-label="本集学习步骤"><button className={view==='episode'?'active':''} onClick={()=>change('episode')}>1. 台词与单词</button><button className={view==='dictation'?'active':''} onClick={()=>change('dictation')}>2. 单词听写</button><button className={view==='speaking'?'active':''} onClick={()=>change('speaking')}>3. 句子跟读</button></nav>{view==='episode'&&<Content episode={episode} change={change}/>} {view==='dictation'&&<Dictation vocab={episode.vocab} refresh={refresh}/>} {view==='speaking'&&<Speaking sentences={episode.sentences} refresh={refresh}/>}<Surface className="finish-card"><Cat size={38}/><div><strong>{finished?'今天的学习小徽章已经收好啦！':'三步都完成后，来领取小猫咪徽章。'}</strong><span>完成一集，就在学习地图上留下一个小爪印。</span></div><Button onClick={()=>void complete()} disabled={finished}>{finished?'已完成本集':'完成本集学习'}</Button></Surface></div>;}
function Content({episode,change}:{episode:Detail;change:(v:View)=>void}){
  const featured=episode.sentences.filter(sentence=>sentence.is_featured);const[audioMessage,setAudioMessage]=useState('');function readSentence(text:string){setAudioMessage(speak(text)?'凑凑喵正在读这句话。':'这台设备暂时不能朗读英文，可以换 Safari、Chrome 或 Edge 试试。');}
  return <div className="episode-content">
    <Surface className="story-pocket">
      <div className="story-pocket__icon"><BookOpen size={30}/></div>
      <div><p className="eyebrow">故事小口袋</p><h2>{episode.chinese_title}</h2><p>{episode.story_summary}</p><p className="story-theme"><PawPrint size={18}/>{episode.story_theme}</p></div>
    </Surface>
    <section className="emotion-path" aria-labelledby="emotion-title">
      <div className="section-heading"><h2 id="emotion-title">Rex 的心情小路</h2><p>看懂心情，故事就懂了一半。</p></div>
      <div><span>期待交朋友</span><span>被误会</span><span>孤单难过</span><span>发现真相</span></div>
    </section>
    <div className="content-columns">
      <Surface className="featured-card">
        <p className="card-kicker">今天先学 4 句</p><h2>故事金句</h2><p className="card-intro">先听、再读，不用一次记住全部。</p>
        <div className="sentence-list">{featured.slice(0,4).map(sentence=><SentenceRow key={sentence.id} sentence={sentence} onSpeak={readSentence}/>)}</div>
        {audioMessage&&<p className="gentle-note" role="status">{audioMessage}</p>}
        {featured.length>4&&<details className="disclosure"><summary>再学 {featured.length-4} 句重点句</summary><div className="sentence-list">{featured.slice(4).map(sentence=><SentenceRow key={sentence.id} sentence={sentence} onSpeak={readSentence}/>)}</div></details>}
        <details className="disclosure"><summary>完整台词（{episode.sentences.length}句）</summary><div className="sentence-list">{episode.sentences.map(sentence=><SentenceRow key={sentence.id} sentence={sentence} onSpeak={readSentence}/>)}</div></details>
      </Surface>
      <Surface className="word-garden">
        <p className="card-kicker">听一听，点一点</p><h2>单词花园</h2><p className="card-intro">先认识最常用的 6 个，剩下的需要时再展开。</p>
        <div className="vocab-list">{episode.vocab.slice(0,6).map(vocab=><VocabRow key={vocab.id} vocab={vocab}/>)}</div>
        {episode.vocab.length>6&&<details className="disclosure"><summary>看看另外 {episode.vocab.length-6} 个单词</summary><div className="vocab-list">{episode.vocab.slice(6).map(vocab=><VocabRow key={vocab.id} vocab={vocab}/>)}</div></details>}
        <Button onClick={()=>change('dictation')}>去单词听写</Button>
      </Surface>
      <Surface className="pattern-card">
        <p className="card-kicker">会替换，就会造句</p><h2>句型小魔法</h2><p className="card-intro">每次打开一个句型，读完例句再试着换一个词。</p>
        <div className="pattern-list">{episode.knowledge.map(knowledge=><details key={knowledge.id}><summary>{knowledge.title}</summary><p>{knowledge.explanation}</p><ul>{knowledge.examples.map(example=><li key={example} lang="en">{example}</li>)}</ul></details>)}</div>
        <Button variant="secondary" onClick={()=>change('speaking')}>去句子跟读</Button>
      </Surface>
      <Surface className="story-challenge">
        <p className="card-kicker">不用写长答案</p><h2>我真的看懂了吗？</h2>
        <details className="disclosure"><summary>打开 6 个故事小问题</summary><ol>{episode.comprehension_questions.map(question=><li key={question}>{question}</li>)}</ol></details>
        <details className="disclosure"><summary>跟着 5 张卡复述故事</summary><ol>{episode.retell_steps.map(step=><li key={step}>{step}</li>)}</ol></details>
      </Surface>
      <Surface className="past-tense-card">
        <p className="card-kicker">故事已经发生过啦</p><h2>过去式小抽屉</h2><p className="card-intro">先眼熟就好，不用一次全部背下来。</p>
        <details className="disclosure"><summary>打开 8 组动作变化</summary><div className="past-tense-grid">{episode.past_tense_pairs.map(pair=><div key={pair.base}><span lang="en">{pair.base}</span><strong lang="en">{pair.past}</strong><small>{pair.meaning}</small></div>)}</div></details>
      </Surface>
    </div>
  </div>;
}
function SentenceRow({sentence,onSpeak}:{sentence:Sentence;onSpeak:(text:string)=>void}){return <article className="sentence-line"><button className="sentence-play" aria-label={`朗读句子：${sentence.english}`} onClick={()=>onSpeak(sentence.english)}><strong lang="en">{sentence.english}</strong><span>{sentence.chinese}</span></button><button className="icon-button" aria-label={`朗读：${sentence.english}`} onClick={()=>onSpeak(sentence.english)}><Volume2 size={22}/></button></article>;}
function VocabRow({vocab}:{vocab:Vocab}){return <article><button className="word-sound" onClick={()=>speak(vocab.word)} aria-label={`朗读单词：${vocab.word}`}><Volume2 size={18}/></button><strong>{vocab.word}</strong><span>{vocab.phonetic}</span><em>{vocab.meaning}</em></article>;}
function ResultCard({result,next,nextDisabled=false,correct}:{result:Result;next:()=>void;nextDisabled?:boolean;correct?:()=>Promise<void>}){return <div className={`result-card ${result.is_correct?'result-card--correct':''}`} role="status"><CheckCircle2 size={24}/><div><strong>{result.message}</strong>{result.similarity!=null&&<span>相似度：{Math.round(result.similarity*100)}%</span>}{!result.is_correct&&correct&&<button className="text-button" onClick={()=>void correct()}>其实我读对了，人工修正</button>}</div><Button variant="secondary" onClick={next} disabled={nextDisabled}>下一题</Button></div>;}
function ExerciseNavigator({index,total,onChange}:{index:number;total:number;onChange:(index:number)=>void}){return <nav className="exercise-nav" aria-label="题目切换"><Button variant="secondary" onClick={()=>onChange(index-1)} disabled={index===0}><ChevronLeft size={20}/>上一题</Button><strong>第 {index+1} / {total} 题</strong><Button variant="secondary" onClick={()=>onChange(index+1)} disabled={index===total-1}>下一题<ChevronRight size={20}/></Button></nav>;}
function Dictation({vocab,refresh}:{vocab:Vocab[];refresh:()=>Promise<void>}){const[i,setI]=useState(0);const[mode,setMode]=useState<'meaning'|'audio'>('meaning');const[answer,setAnswer]=useState('');const[result,setResult]=useState<Result|null>(null);const v=vocab[i];async function submit(e:React.FormEvent){e.preventDefault();setResult(await api<Result>('/practice/dictation',{method:'POST',body:JSON.stringify({vocab_id:v.id,answer,mode})}));await refresh();}function goTo(index:number){if(index<0||index>=vocab.length)return;setI(index);setAnswer('');setResult(null);}return <Surface className="practice-card"><p className="eyebrow"><Headphones size={18}/> 单词听写</p><h2>{mode==='meaning'?'看中文，写英文':'听一听，写英文'}</h2><div className="mode-switch"><button className={mode==='meaning'?'active':''} onClick={()=>setMode('meaning')}>看中文</button><button className={mode==='audio'?'active':''} onClick={()=>{setMode('audio');speak(v.word);}}>听发音</button></div><p className="prompt">{mode==='meaning'?v.meaning:'点击下面按钮，再听一次'}</p>{mode==='audio'&&<Button variant="secondary" onClick={()=>speak(v.word)}><Volume2 size={20}/> 再听一次</Button>}<form onSubmit={submit}><label htmlFor="dictation-answer">我写的是</label><input id="dictation-answer" value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="输入英文单词" required/><Button type="submit">交给凑凑喵检查</Button></form>{result&&<ResultCard result={result} next={()=>goTo(i+1)} nextDisabled={i===vocab.length-1}/>}<ExerciseNavigator index={i} total={vocab.length} onChange={goTo}/></Surface>;}
function Speaking({sentences,refresh}:{sentences:Sentence[];refresh:()=>Promise<void>}){const[i,setI]=useState(0);const[transcript,setTranscript]=useState('');const[recording,setRecording]=useState(false);const[result,setResult]=useState<Result|null>(null);const rec=useRef<MediaRecorder|null>(null);const recognition=useRef<BrowserRecognition|null>(null);const s=sentences[i];function goTo(index:number){if(index<0||index>=sentences.length)return;if(recording){rec.current?.stop();recognition.current?.stop();setRecording(false);}setI(index);setTranscript('');setResult(null);}async function toggle(){if(recording){rec.current?.stop();recognition.current?.stop();setRecording(false);return;}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const current=new MediaRecorder(stream);current.onstop=()=>stream.getTracks().forEach(t=>t.stop());current.start();rec.current=current;const Recognition=(window as unknown as {SpeechRecognition?:BrowserRecognitionConstructor;webkitSpeechRecognition?:BrowserRecognitionConstructor}).SpeechRecognition??(window as unknown as {webkitSpeechRecognition?:BrowserRecognitionConstructor}).webkitSpeechRecognition;if(Recognition){const listener=new Recognition();listener.lang='en-US';listener.interimResults=false;listener.onresult=event=>setTranscript(event.results[0]?.[0]?.transcript??'');listener.start();recognition.current=listener;}setRecording(true);}catch{setResult({attempt_id:'',is_correct:false,message:'麦克风还没有准备好，可以把你读到的句子填在下面。'});}}async function submit(e:React.FormEvent){e.preventDefault();setResult(await api<Result>('/practice/speaking',{method:'POST',body:JSON.stringify({sentence_id:s.id,transcript})}));await refresh();}async function correct(){if(result?.attempt_id){setResult(await api<Result>(`/practice/attempts/${result.attempt_id}/correct`,{method:'POST'}));await refresh();}}return <Surface className="practice-card"><p className="eyebrow"><Mic size={18}/> 句子跟读</p><h2 lang="en">{s.english}</h2><p className="prompt">{s.chinese}</p><div className="practice-actions"><Button variant="secondary" onClick={()=>speak(s.english)}><Volume2 size={20}/> 先听一遍</Button><Button onClick={()=>void toggle()}>{recording?<Pause size={20}/>:<Mic size={20}/>}{recording?'结束录音':'开始录音'}</Button></div><form onSubmit={submit}><label htmlFor="transcript">凑凑喵听到的是</label><textarea id="transcript" value={transcript} onChange={e=>setTranscript(e.target.value)} placeholder="录音后会自动识别；也可以在这里修正文字" required/><Button type="submit">看看读得怎么样</Button></form><ExerciseNavigator index={i} total={sentences.length} onChange={goTo}/>{result&&<ResultCard result={result} correct={correct} next={()=>goTo(i+1)} nextDisabled={i===sentences.length-1}/>}</Surface>;}
