import { BookOpen, Cat, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, Fish, Headphones, Mic, Pause, PawPrint, Play, Sparkles, Volume2 } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { AppShell } from './components/layout/AppShell';
import { BrandMark } from './components/brand/BrandMark';
import { Button } from './components/ui/Button';
import { Surface } from './components/ui/Surface';
import { GrowthRecord } from './components/progress/GrowthRecord';
import { useEnglishSpeech } from './hooks/useEnglishSpeech';
import { useLearningProgress } from './hooks/useLearningProgress';
import { getDemoGrowthSummary } from './progress/demoGrowthSummary';
import type { LearningItem } from './progress/localProgressRepository';
import type { CurriculumLesson } from './curriculum/types';
import { useSchoolProgress } from './hooks/useSchoolProgress';
import { SchoolLesson } from './components/school/SchoolLesson';
import { SchoolLibrary } from './components/school/SchoolLibrary';
import { SchoolToday } from './components/school/SchoolToday';
import { DualTrackGrowth } from './components/progress/DualTrackGrowth';
import { getLessonById } from './curriculum/pepGrade4UpperUnit1';
import { localExtraApi } from './extra/localExtraContent';
type Episode={id:string;level:number;series_title:string;episode_number:number;title:string;local_video_filename:string;is_published:boolean;is_learned:boolean};type Sentence={id:string;english:string;chinese:string;is_featured:boolean};type Vocab={id:string;word:string;phonetic:string;meaning:string};type Knowledge={id:string;title:string;explanation:string;examples:string[]};type PastTensePair={base:string;past:string;meaning:string};type Detail=Episode&{chinese_title:string;story_summary:string;story_theme:string;sentences:Sentence[];vocab:Vocab[];knowledge:Knowledge[];comprehension_questions:string[];retell_steps:string[];past_tense_pairs:PastTensePair[]};type Stats={learned_episodes:number;total_words:number;practice_count:number;mistake_count:number};type AnswerMethod='written'|'spoken'|'sentence_reading';type Result={attempt_id:string;is_correct:boolean;message:string;similarity?:number;answer_method?:AnswerMethod};type View='home'|'episode'|'dictation'|'speaking'|'school-lesson'|'login';
type BrowserRecognition={lang:string;interimResults:boolean;onresult:((event:{results:ArrayLike<ArrayLike<{transcript:string}>>})=>void)|null;start:()=>void;stop:()=>void};type BrowserRecognitionConstructor=new()=>BrowserRecognition;type HomeSection='today'|'school'|'extra'|'bookshelf'|'progress';
const base=import.meta.env.VITE_API_BASE_URL??'http://localhost:8000';async function api<T>(path:string,init?:RequestInit):Promise<T>{try{const r=await fetch(`${base}/api/v1${path}`,{headers:{'Content-Type':'application/json',...init?.headers},...init});if(!r.ok)throw new Error('暂不可用');return r.json() as Promise<T>;}catch(error){try{return localExtraApi(path,init) as T;}catch{throw error;}}}function speak(text:string){const synthesis=window.speechSynthesis;if(!synthesis||typeof window.SpeechSynthesisUtterance!=='function')return false;const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.82;synthesis.cancel();synthesis.speak(u);return true;}
export function App(){
  const[view,setView]=useState<View>('home');const[homeSection,setHomeSection]=useState<HomeSection>('today');const[episodes,setEpisodes]=useState<Episode[]>([]);const[stats,setStats]=useState<Stats>({learned_episodes:0,total_words:0,practice_count:0,mistake_count:0});const[episode,setEpisode]=useState<Detail|null>(null);const[schoolLesson,setSchoolLesson]=useState<CurriculumLesson|null>(null);const[schoolInitialStep,setSchoolInitialStep]=useState<'learn'|'practice'|'check'>('learn');const[reviewItem,setReviewItem]=useState<LearningItem|null>(null);const[error,setError]=useState('');const[profile,setProfile]=useState('小咪');const progress=useLearningProgress();const school=useSchoolProgress();const params=new URLSearchParams(window.location.search);const motion=params.get('ui')==='motion';const visibleProgress=params.get('demo')==='growth'?getDemoGrowthSummary():progress.summary;
  useEffect(()=>{let alive=true;void(async()=>{try{const list=await api<{items:Episode[]}>('/episodes');const current=await api<Stats>('/stats');if(alive){setEpisodes(list.items);setStats(current);}}catch{if(alive)setError('课外动画暂时没有连上，校内学习可以照常开始。');}})();return()=>{alive=false;};},[]);
  async function open(id:string,target:View='episode',item:LearningItem|null=null){try{setEpisode(await api<Detail>(`/episodes/${id}`));setReviewItem(item);setView(target);setError('');}catch{setError('这一集还没准备好，请稍后再试。');}}
  const openSchoolLesson=(lesson:CurriculumLesson,initialStep:'learn'|'practice'|'check'='learn')=>{setSchoolLesson(lesson);setSchoolInitialStep(initialStep);setView('school-lesson');};
  const openReview=(item:LearningItem)=>open(item.episodeId,item.kind==='word'?'dictation':item.kind==='sentence'?'speaking':'episode',item);async function refresh(){setStats(await api<Stats>('/stats'));}
  const backToBookshelf=()=>{setReviewItem(null);setHomeSection(motion?'extra':'bookshelf');setView('home');};
  return <AppShell variant={motion?'motion':'classic'} showHeader={!motion||view!=='home'}>
    {view==='home'?(motion?<MotionHome episodes={episodes} progress={visibleProgress} school={school} error={error} profile={profile} open={open} openSchoolLesson={openSchoolLesson} review={openReview} login={()=>setView('login')} section={homeSection} setSection={setHomeSection}/>:<Home episodes={episodes} stats={stats} progress={visibleProgress} error={error} profile={profile} open={open} review={openReview} login={()=>setView('login')} section={homeSection} setSection={setHomeSection}/>):view==='school-lesson'&&schoolLesson?<SchoolLesson initialStep={schoolInitialStep} lesson={schoolLesson} onRecordExercise={school.recordExercise} onComplete={lesson=>{school.completeLesson(lesson);setHomeSection('school');setView('home');}} onBack={()=>{setHomeSection('school');setView('home');}} storageError={school.storageError}/>:view==='login'?<Login done={name=>{setProfile(name);setView('home');}}/>:episode?<Learning view={view} episode={episode} reviewItem={reviewItem} back={backToBookshelf} change={setView} refresh={refresh} progress={progress}/>:null}
  </AppShell>;
}

function MotionHome({episodes,progress,school,error,profile,open,openSchoolLesson,review,login,section,setSection}:{episodes:Episode[];progress:ReturnType<typeof useLearningProgress>['summary'];school:ReturnType<typeof useSchoolProgress>;error:string;profile:string;open:(id:string,target?:View)=>void;openSchoolLesson:(lesson:CurriculumLesson,initialStep?:'learn'|'practice'|'check')=>void;review:(item:LearningItem)=>void;login:()=>void;section:HomeSection;setSection:(section:HomeSection)=>void}){
  const animation=episodes.find(item=>!item.is_learned)??episodes[0];
  const currentLesson=school.currentLesson;
  if(!currentLesson)return <Surface><h2>今天还没有校内任务</h2><p className="empty-state">凑凑喵正在整理下一课。</p></Surface>;
  return <><section className="motion-home" aria-label="今日校内学习舞台">
    <video className="motion-home__video" autoPlay loop muted playsInline preload="auto" disableRemotePlayback poster="https://images.unsplash.com/photo-1557683316-973673baf926?w=1600&q=60" aria-hidden="true"><source src="https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260424_064411_9e9d7f84-9277-41f4-ab10-59172d89e6be.mp4" type="video/mp4" /></video>
    <div className="motion-home__veil" aria-hidden="true" />
    <div className="motion-home__content">
      <header className="motion-home__nav"><BrandMark/><nav aria-label="首页内容"><button className={section==='today'?'active':''} onClick={()=>setSection('today')}>今日学习</button><button className={section==='school'?'active':''} onClick={()=>setSection('school')}>校内同步</button><button className={section==='extra'?'active':''} onClick={()=>setSection('extra')}>课外动画</button><button className={section==='progress'?'active':''} onClick={()=>setSection('progress')}>成长记录</button></nav><button className="motion-profile" onClick={login}><Cat size={18}/>{profile}</button></header>
      {section==='today'&&<SchoolToday lesson={currentLesson} completedCount={school.summary.completedLessonIds.length} onStart={()=>openSchoolLesson(currentLesson)}/>}
      {section==='school'&&<SchoolLibrary completedLessonIds={school.summary.completedLessonIds} currentLessonId={school.summary.currentLessonId} onOpenLesson={openSchoolLesson} onOpenExtra={()=>setSection('extra')}/>}
      {section==='extra'&&<MotionBookshelf episodes={episodes} open={open}/>}
      {section==='progress'&&<div className="motion-home__panel"><DualTrackGrowth school={school.summary} extra={progress} onStartSchool={()=>openSchoolLesson(currentLesson)} onStartExtra={()=>setSection('extra')} onSchoolReview={item=>{const lesson=getLessonById(item.lessonId);if(lesson)openSchoolLesson(lesson);}} onExtraReview={review}/></div>}
      {section==='extra'&&error&&<p className="gentle-note motion-home__error" role="status">{error}</p>}
    </div>
  </section>{section==='today'&&<section className="motion-home__journey" aria-label="今日校内学习路径"><section className="motion-task-tray" aria-labelledby="motion-task-title"><div className="motion-task-tray__heading"><div><p>SCHOOL PATH</p><h3 id="motion-task-title">三步完成今天的校内任务</h3><p className="motion-task-tray__intro">先学课本，再做练习，最后用小检查收尾。</p></div></div><div className="motion-task-tray__steps"><button onClick={()=>openSchoolLesson(currentLesson,'learn')}><span>01</span><BookOpen size={24}/><div><strong>学课本</strong><small>单词、句型和拼读</small></div><ChevronRight size={20}/></button><button onClick={()=>openSchoolLesson(currentLesson,'practice')}><span>02</span><Headphones size={24}/><div><strong>练一练</strong><small>听、读、选和写</small></div><ChevronRight size={20}/></button><button onClick={()=>openSchoolLesson(currentLesson,'check')}><span>03</span><CheckCircle2 size={24}/><div><strong>小检查</strong><small>看看今天学会了吗</small></div><ChevronRight size={20}/></button></div></section>{animation&&<section className="school-extra-card"><div><p>动画加餐 · 课外</p><h3>{animation.title}</h3><span>学完校内任务后，用动画轻松复习 family、help 和 can。</span></div><Button variant="secondary" onClick={()=>setSection('extra')}>去课外动画</Button></section>}</section>}</>;
}
function MotionBookshelf({episodes,open}:{episodes:Episode[];open:(id:string,target?:View)=>void}){const[level,setLevel]=useState(1);const[series,setSeries]=useState('');return <section className="motion-home__panel"><div className="section-heading"><p className="eyebrow"><BookOpen size={18}/> STORY LIBRARY</p><h2>动画学习小书架</h2><p>先选 Level，再选剧集，最后开始其中的一集。</p></div><div className="level-list">{Array.from({length:9},(_,i)=>i+1).map(n=>{const items=episodes.filter(item=>item.level===n);const seriesTitles=[...new Set(items.map(item=>item.series_title))];return <div className="level-card" key={n}><button className="level-card__button" onClick={()=>{setLevel(level===n?0:n);setSeries('');}} aria-expanded={level===n}><span>Level {n}</span><span>{items.length?`${items.length} 集已发布`:'等待整理'}<ChevronDown size={20}/></span></button>{level===n&&<div className="level-card__content">{items.length?<div className="series-list">{seriesTitles.map(seriesTitle=>{const seriesEpisodes=items.filter(item=>item.series_title===seriesTitle).sort((a,b)=>a.episode_number-b.episode_number);return <div className="series-card" key={seriesTitle}><button className="series-card__button" onClick={()=>setSeries(series===seriesTitle?'':seriesTitle)} aria-expanded={series===seriesTitle}><span>{seriesTitle}</span><span>{seriesEpisodes.length} 集 <ChevronDown size={18}/></span></button>{series===seriesTitle&&<div className="series-card__content">{seriesEpisodes.map(item=><div className="episode-row" key={item.id}><div><strong>第 {item.episode_number} 集 · {item.title}</strong><span>{item.is_learned?'已经学过，真棒！':'准备好一起开始啦'}</span></div><Button onClick={()=>open(item.id)}>开始学习</Button></div>)}</div>}</div>;})}</div>:<p className="empty-state">凑凑喵正在把这一层的小故事整理得清清楚楚。</p>}</div>}</div>;})}</div></section>}
function MotionProgress({stats}:{stats:Stats}){return <section className="motion-home__panel"><div className="section-heading"><p className="eyebrow"><PawPrint size={18}/> MY LITTLE STEPS</p><h2>我的成长记录</h2><p>每次认真练习，都会留下一个小脚印。</p></div><div className="stat-grid">{[['已学剧集',stats.learned_episodes,'集'],['累计单词',stats.total_words,'个'],['练习次数',stats.practice_count,'次'],['需要复习',stats.mistake_count,'项']].map(([label,value,unit])=><Surface className="stat" key={label}><strong>{value}<small>{unit}</small></strong><span>{label}</span></Surface>)}</div></section>}
function Home({episodes,stats,progress,error,profile,open,review,login,section,setSection}:{episodes:Episode[];stats:Stats;progress:ReturnType<typeof useLearningProgress>['summary'];error:string;profile:string;open:(id:string,target?:View)=>void;review:(item:LearningItem)=>void;login:()=>void;section:HomeSection;setSection:(section:HomeSection)=>void}){
  const[level,setLevel]=useState(1);const[series,setSeries]=useState('');const today=episodes.find(item=>!item.is_learned)??episodes[0];
  return <div className="page-stack home">
    <section className="welcome-panel home-welcome"><div><p className="eyebrow"><Sparkles size={18}/> 嗨，{profile}</p><h2>今天继续学习</h2><p>凑凑喵已经把今天的任务排好啦。</p></div><div className="mascot" aria-label="凑凑喵"><Cat size={68}/><PawPrint className="mascot__paw" size={24}/></div><Button variant="secondary" onClick={login}>切换小伙伴</Button></section>
    <nav className="home-nav" aria-label="首页内容"><button className={section==='today'?'active':''} onClick={()=>setSection('today')}>今日学习</button><button className={section==='bookshelf'?'active':''} onClick={()=>setSection('bookshelf')}>剧集书架</button><button className={section==='progress'?'active':''} onClick={()=>setSection('progress')}>成长记录</button></nav>
    {section==='today'&&<div className="home-section">{today?<><Surface className="continue-card"><div><p className="eyebrow"><Fish size={18}/> 今天就学这一集</p><h2>Level {today.level} · {today.series_title}</h2><p>第 {today.episode_number} 集 · {today.title}</p><p>先看懂故事，再练单词，最后勇敢开口。</p></div><Button onClick={()=>open(today.id)}>继续学习</Button></Surface><section className="story-map"><div className="section-heading"><h2>三步完成今天的任务</h2><p>想从哪一步开始都可以。</p></div><div className="story-map__steps"><button onClick={()=>open(today.id,'episode')}><span>1</span><BookOpen size={24}/><strong>看故事学英语</strong><small>台词、单词和句型</small></button><button onClick={()=>open(today.id,'dictation')}><span>2</span><Headphones size={24}/><strong>单词听写</strong><small>看中文或听发音</small></button><button onClick={()=>open(today.id,'speaking')}><span>3</span><Mic size={24}/><strong>句子跟读</strong><small>录音并检查发音</small></button></div></section></>:<Surface><h2>今天还没有学习任务</h2><p className="empty-state">请先到剧集书架看看已经整理好的内容。</p><Button onClick={()=>setSection('bookshelf')}>打开剧集书架</Button></Surface>}</div>}
    {section==='bookshelf'&&<section className="home-section"><div className="section-heading"><h2>动画学习小书架</h2><p>先选 Level，再选剧集，最后开始其中的一集。</p></div><div className="level-list">{Array.from({length:9},(_,i)=>i+1).map(n=>{const items=episodes.filter(item=>item.level===n);const seriesTitles=[...new Set(items.map(item=>item.series_title))];return <div className="level-card" key={n}><button className="level-card__button" onClick={()=>{setLevel(level===n?0:n);setSeries('');}} aria-expanded={level===n}><span>Level {n}</span><span>{items.length?`${items.length} 集已发布`:'等待整理'}<ChevronDown size={20}/></span></button>{level===n&&<div className="level-card__content">{items.length?<div className="series-list">{seriesTitles.map(seriesTitle=>{const seriesEpisodes=items.filter(item=>item.series_title===seriesTitle).sort((a,b)=>a.episode_number-b.episode_number);return <div className="series-card" key={seriesTitle}><button className="series-card__button" onClick={()=>setSeries(series===seriesTitle?'':seriesTitle)} aria-expanded={series===seriesTitle}><span>{seriesTitle}</span><span>{seriesEpisodes.length} 集 <ChevronDown size={18}/></span></button>{series===seriesTitle&&<div className="series-card__content">{seriesEpisodes.map(item=><div className="episode-row" key={item.id}><div><strong>第 {item.episode_number} 集 · {item.title}</strong><span>{item.is_learned?'已经学过，真棒！':'准备好一起开始啦'}</span></div><Button onClick={()=>open(item.id)}>开始学习</Button></div>)}</div>}</div>;})}</div>:<p className="empty-state">凑凑喵正在把这一层的小故事整理得清清楚楚。</p>}</div>}</div>;})}</div></section>}
    {section==='progress'&&<GrowthRecord summary={progress} onStartLearning={()=>setSection('today')} onReviewItem={review}/>}
    {error&&<p className="gentle-note" role="status">{error}</p>}
  </div>;
}
function Login({done}:{done:(name:string)=>void}){const[email,setEmail]=useState('parent@example.com');const[msg,setMsg]=useState('');async function submit(e:React.FormEvent){e.preventDefault();try{const data=await api<{profile:{display_name:string}}>('/auth/login',{method:'POST',body:JSON.stringify({email})});setMsg('欢迎回来，凑凑喵已经准备好啦。');done(data.profile.display_name);}catch{setMsg('请检查邮箱后再试试。');}}return <Surface className="login-card"><p className="eyebrow"><Sparkles size={18}/> 家长登录</p><h2>把学习脚印带回来</h2><p>测试阶段使用家庭演示登录；接入 Supabase 后会自动替换为真实账户。</p><form onSubmit={submit}><label htmlFor="email">家长邮箱</label><input id="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><Button type="submit">进入乐园</Button></form>{msg&&<p className="gentle-note" role="status">{msg}</p>}</Surface>;}
function Learning({view,episode,reviewItem,back,change,refresh,progress}:{view:View;episode:Detail;reviewItem:LearningItem|null;back:()=>void;change:(v:View)=>void;refresh:()=>Promise<void>;progress:ReturnType<typeof useLearningProgress>}){const[finished,setFinished]=useState(false);async function complete(){await api(`/episodes/${episode.id}/learned`,{method:'POST'});progress.markEpisode(episode);await refresh();setFinished(true);}return <div className="page-stack"><button className="back-link" onClick={back}><ChevronLeft size={20}/> 回到小书架</button><div className="episode-heading"><p className="eyebrow">Level {episode.level} · {episode.series_title} · 第 {episode.episode_number} 集</p><h2>{episode.title}</h2><p className="video-cue"><BookOpen size={20}/><span>请在本地打开对应视频观看</span>：<strong>{episode.local_video_filename}</strong></p></div><nav className="learning-nav" aria-label="本集学习步骤"><button className={view==='episode'?'active':''} onClick={()=>change('episode')}>1. 看故事学英语</button><button className={view==='dictation'?'active':''} onClick={()=>change('dictation')}>2. 单词听写</button><button className={view==='speaking'?'active':''} onClick={()=>change('speaking')}>3. 句子跟读</button></nav>{view==='episode'&&<Content episode={episode} change={change} markPattern={progress.markPattern}/>} {view==='dictation'&&<Dictation key={reviewItem?.id??'dictation'} vocab={episode.vocab} episodeId={episode.id} initialItemId={reviewItem?.kind==='word'?reviewItem.id:undefined} refresh={refresh} record={progress.recordDictation}/>} {view==='speaking'&&<Speaking key={reviewItem?.id??'speaking'} sentences={episode.sentences} episodeId={episode.id} initialItemId={reviewItem?.kind==='sentence'?reviewItem.id:undefined} record={progress.recordSentence}/>}<Surface className="finish-card"><Cat size={38}/><div><strong>{finished?'今天的学习小徽章已经收好啦！':'三步都完成后，来领取小猫咪徽章。'}</strong><span>完成一集，就在学习地图上留下一个小爪印。</span></div><Button onClick={()=>void complete()} disabled={finished}>{finished?'已完成本集':'完成本集学习'}</Button></Surface></div>;}
function Content({episode,change,markPattern}:{episode:Detail;change:(v:View)=>void;markPattern:ReturnType<typeof useLearningProgress>['markPattern']}){
  const featured=episode.sentences.filter(sentence=>sentence.is_featured);const narrator=useEnglishSpeech();function readSentence(text:string,key:string){narrator.speak(text,key);}
  return <div className="episode-content">
    <Surface className="story-pocket">
      <div className="story-pocket__icon"><BookOpen size={30}/></div>
      <div><p className="eyebrow">故事小口袋</p><h2>{episode.chinese_title}</h2><p>{episode.story_summary}</p><p className="story-theme"><PawPrint size={18}/>{episode.story_theme}</p></div>
    </Surface>
    <section className="emotion-path" aria-labelledby="emotion-title">
      <div className="section-heading"><h2 id="emotion-title">Rex 的心情小路</h2><p>看懂心情，故事就懂了一半。</p></div>
      <div><span>期待交朋友</span><span>被误会</span><span>孤单难过</span><span>发现真相</span></div>
    </section>
    <div className="content-columns">
      <Surface className="featured-card">
        <p className="card-kicker">今天先学 4 句</p><h2>故事金句</h2><p className="card-intro">先听、再读，不用一次记住全部。</p>
        <div className="sentence-list">{featured.slice(0,4).map(sentence=><SentenceRow key={sentence.id} sentence={sentence} speakerKey={`featured-${sentence.id}`} onSpeak={readSentence} isSpeaking={narrator.phase==='speaking'&&narrator.activeKey===`featured-${sentence.id}`} message={narrator.activeKey===`featured-${sentence.id}`?narrator.message:''}/>)}</div>
        {featured.length>4&&<details className="disclosure"><summary>再学 {featured.length-4} 句重点句</summary><div className="sentence-list">{featured.slice(4).map(sentence=><SentenceRow key={sentence.id} sentence={sentence} speakerKey={`extra-${sentence.id}`} onSpeak={readSentence} isSpeaking={narrator.phase==='speaking'&&narrator.activeKey===`extra-${sentence.id}`} message={narrator.activeKey===`extra-${sentence.id}`?narrator.message:''}/>)}</div></details>}
        <details className="disclosure"><summary>完整台词（{episode.sentences.length}句）</summary><div className="sentence-list">{episode.sentences.map(sentence=><SentenceRow key={sentence.id} sentence={sentence} speakerKey={`all-${sentence.id}`} onSpeak={readSentence} isSpeaking={narrator.phase==='speaking'&&narrator.activeKey===`all-${sentence.id}`} message={narrator.activeKey===`all-${sentence.id}`?narrator.message:''}/>)}</div></details>
      </Surface>
      <Surface className="word-garden">
        <p className="card-kicker">听一听，点一点</p><h2>单词花园</h2><p className="card-intro">先认识最常用的 6 个，剩下的需要时再展开。</p>
        <div className="vocab-list">{episode.vocab.slice(0,6).map(vocab=><VocabRow key={vocab.id} vocab={vocab}/>)}</div>
        {episode.vocab.length>6&&<details className="disclosure"><summary>看看另外 {episode.vocab.length-6} 个单词</summary><div className="vocab-list">{episode.vocab.slice(6).map(vocab=><VocabRow key={vocab.id} vocab={vocab}/>)}</div></details>}
        <div className="word-garden__action"><Button aria-label="开始单词听写" onClick={()=>change('dictation')}>去单词听写</Button></div>
      </Surface>
      <Surface className="pattern-card">
        <p className="card-kicker">会替换，就会造句</p><h2>句型小魔法</h2><p className="card-intro">每次打开一个句型，读完例句再试着换一个词。</p>
        <div className="pattern-list">{episode.knowledge.map(knowledge=><details key={knowledge.id}><summary>{knowledge.title}</summary><p>{knowledge.explanation}</p><ul>{knowledge.examples.map(example=><li key={example} lang="en">{example}</li>)}</ul><Button variant="secondary" onClick={()=>markPattern(knowledge,episode.id)} aria-label={`收下句式：${knowledge.title}`}>我会这个句式</Button></details>)}</div>
        <Button variant="secondary" onClick={()=>change('speaking')}>去句子跟读</Button>
      </Surface>
      <Surface className="story-challenge">
        <p className="card-kicker">不用写长答案</p><h2>我真的看懂了吗？</h2>
        <details className="disclosure"><summary>打开 6 个故事小问题</summary><ol>{episode.comprehension_questions.map(question=><li key={question}>{question}</li>)}</ol></details>
        <details className="disclosure"><summary>跟着 5 张卡复述故事</summary><ol>{episode.retell_steps.map(step=><li key={step}>{step}</li>)}</ol></details>
      </Surface>
      <Surface className="past-tense-card">
        <p className="card-kicker">故事已经发生过啦</p><h2>过去式小抽屉</h2><p className="card-intro">先眼熟就好，不用一次全部背下来。</p>
        <details className="disclosure"><summary>打开 8 组动作变化</summary><div className="past-tense-grid">{episode.past_tense_pairs.map(pair=><div key={pair.base}><span lang="en">{pair.base}</span><strong lang="en">{pair.past}</strong><small>{pair.meaning}</small></div>)}</div></details>
      </Surface>
    </div>
  </div>;
}
function SentenceRow({sentence,speakerKey,onSpeak,isSpeaking=false,message=''}:{sentence:Sentence;speakerKey:string;onSpeak:(text:string,key:string)=>void;isSpeaking?:boolean;message?:string}){return <article className="sentence-line"><button className="sentence-play" aria-label={`朗读句子：${sentence.english}`} onClick={()=>onSpeak(sentence.english,speakerKey)}><strong lang="en">{sentence.english}</strong><span>{sentence.chinese}</span></button><button className="icon-button" aria-label={`朗读：${sentence.english}`} aria-pressed={isSpeaking} onClick={()=>onSpeak(sentence.english,speakerKey)}><Volume2 size={22}/></button>{message&&<p className="speech-feedback" role="status" aria-live="polite">{message}</p>}</article>;}
function VocabRow({vocab}:{vocab:Vocab}){return <article><button className="word-sound" onClick={()=>speak(vocab.word)} aria-label={`朗读单词：${vocab.word}`}><Volume2 size={18}/></button><strong>{vocab.word}</strong><span>{vocab.phonetic}</span><em>{vocab.meaning}</em></article>;}
function ResultCard({result,next,nextDisabled=false,correct}:{result:Result;next:()=>void;nextDisabled?:boolean;correct?:()=>Promise<void>}){return <div className={`result-card ${result.is_correct?'result-card--correct':''}`} role="status"><CheckCircle2 size={24}/><div><strong>{result.message}</strong>{result.similarity!=null&&<span>相似度：{Math.round(result.similarity*100)}%</span>}{!result.is_correct&&correct&&<button className="text-button" onClick={()=>void correct()}>其实我读对了，人工修正</button>}</div><Button variant="secondary" onClick={next} disabled={nextDisabled}>下一题</Button></div>;}
function ExerciseNavigator({index,total,onChange}:{index:number;total:number;onChange:(index:number)=>void}){return <nav className="exercise-nav" aria-label="题目切换"><Button variant="secondary" onClick={()=>onChange(index-1)} disabled={index===0}><ChevronLeft size={20}/>上一题</Button><strong>第 {index+1} / {total} 题</strong><Button variant="secondary" onClick={()=>onChange(index+1)} disabled={index===total-1}>下一题<ChevronRight size={20}/></Button></nav>;}
function Dictation({vocab,episodeId,initialItemId,refresh,record}:{vocab:Vocab[];episodeId:string;initialItemId?:string;refresh:()=>Promise<void>;record:ReturnType<typeof useLearningProgress>['recordDictation']}){
  const initialIndex=Math.max(0,initialItemId?vocab.findIndex(item=>item.id===initialItemId):0);const[i,setI]=useState(initialIndex);const[mode,setMode]=useState<'meaning'|'audio'>('meaning');const[answerMethod,setAnswerMethod]=useState<Extract<AnswerMethod,'written'|'spoken'>>('written');const[answer,setAnswer]=useState('');const[result,setResult]=useState<Result|null>(null);const[speechHint,setSpeechHint]=useState('');const[listening,setListening]=useState(false);const recognition=useRef<BrowserRecognition|null>(null);const v=vocab[i];
  function stopListening(){recognition.current?.stop();setListening(false);}
  function chooseMethod(next:Extract<AnswerMethod,'written'|'spoken'>){stopListening();setAnswerMethod(next);setAnswer('');setResult(null);setSpeechHint('');}
  function startListening(){if(listening){stopListening();return;}const Recognition=(window as unknown as {SpeechRecognition?:BrowserRecognitionConstructor;webkitSpeechRecognition?:BrowserRecognitionConstructor}).SpeechRecognition??(window as unknown as {webkitSpeechRecognition?:BrowserRecognitionConstructor}).webkitSpeechRecognition;if(!Recognition){setSpeechHint('这台设备暂时不能自动识别语音，你可以请大人帮忙确认，或把说出的单词填在下面。');return;}const listener=new Recognition();listener.lang='en-US';listener.interimResults=false;listener.onresult=event=>{const heard=event.results[0]?.[0]?.transcript??'';setAnswer(heard);setSpeechHint(heard?`凑凑喵听到：${heard}`:'凑凑喵还没听清，再说一遍吧。');};listener.start();recognition.current=listener;setListening(true);setSpeechHint('凑凑喵正在认真听，请说出英文单词。');}
  async function submit(e:React.FormEvent){e.preventDefault();stopListening();const next=await api<Result>('/practice/dictation',{method:'POST',body:JSON.stringify({vocab_id:v.id,answer,mode,answer_method:answerMethod})});setResult(next);record(v,episodeId,next.is_correct,answerMethod);await refresh();}
  function goTo(index:number){if(index<0||index>=vocab.length)return;stopListening();setI(index);setAnswer('');setResult(null);setSpeechHint('');}
  const prompt=mode==='meaning'?v.meaning:'点击下面按钮，再听一次';const title=answerMethod==='spoken'?(mode==='meaning'?'看中文，说英文':'听一听，说英文'):(mode==='meaning'?'看中文，写英文':'听一听，写英文');
  return <Surface className="practice-card"><p className="eyebrow"><Headphones size={18}/> 单词听写</p><h2>{title}</h2><div className="mode-switch" aria-label="出题方式"><button className={mode==='meaning'?'active':''} onClick={()=>setMode('meaning')}>看中文</button><button className={mode==='audio'?'active':''} onClick={()=>{setMode('audio');speak(v.word);}}>听发音</button></div><div className="mode-switch" aria-label="作答方式"><button className={answerMethod==='written'?'active':''} onClick={()=>chooseMethod('written')}>写出来</button><button className={answerMethod==='spoken'?'active':''} onClick={()=>chooseMethod('spoken')}>说出来</button></div><p className="prompt">{prompt}</p>{mode==='audio'&&<Button variant="secondary" onClick={()=>speak(v.word)}><Volume2 size={20}/> 再听一次</Button>}<form onSubmit={submit}>{answerMethod==='spoken'&&<div className="practice-actions"><Button type="button" variant="secondary" onClick={startListening}>{listening?<Pause size={20}/>:<Mic size={20}/>}{listening?'结束聆听':'点击说单词'}</Button>{speechHint&&<p className="gentle-note" role="status">{speechHint}</p>}</div>}<label htmlFor="dictation-answer">{answerMethod==='written'?'我写的是':'凑凑喵听到的是'}</label><input id="dictation-answer" value={answer} onChange={e=>setAnswer(e.target.value)} placeholder={answerMethod==='written'?'输入英文单词':'说完后会显示在这里，也可以修正'} required/><Button type="submit">交给凑凑喵检查</Button></form>{result&&<ResultCard result={result} next={()=>goTo(i+1)} nextDisabled={i===vocab.length-1}/>}<ExerciseNavigator index={i} total={vocab.length} onChange={goTo}/></Surface>;
}
function Speaking({sentences,episodeId,initialItemId,record}:{sentences:Sentence[];episodeId:string;initialItemId?:string;record:ReturnType<typeof useLearningProgress>['recordSentence']}){
  const initialIndex=Math.max(0,initialItemId?sentences.findIndex(item=>item.id===initialItemId):0);const[i,setI]=useState(initialIndex);const[recording,setRecording]=useState(false);const[recordingUrl,setRecordingUrl]=useState('');const[message,setMessage]=useState('');const[result,setResult]=useState<Result|null>(null);const rec=useRef<MediaRecorder|null>(null);const chunks=useRef<Blob[]>([]);const s=sentences[i];
  function goTo(index:number){if(index<0||index>=sentences.length)return;if(recording)rec.current?.stop();setRecording(false);if(recordingUrl)URL.revokeObjectURL(recordingUrl);setI(index);setRecordingUrl('');setMessage('');setResult(null);}
  async function toggle(){if(recording){rec.current?.stop();setRecording(false);return;}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const current=new MediaRecorder(stream);chunks.current=[];current.ondataavailable=event=>{if(event.data.size)chunks.current.push(event.data);};current.onstop=()=>{stream.getTracks().forEach(track=>track.stop());if(chunks.current.length){if(recordingUrl)URL.revokeObjectURL(recordingUrl);setRecordingUrl(URL.createObjectURL(new Blob(chunks.current,{type:current.mimeType||'audio/webm'})));setMessage('录音收好啦，先听一听自己的声音，再完成这一句。');}};current.start();rec.current=current;setMessage('正在录音，读完后点“结束录音”。');setRecording(true);}catch{setMessage('麦克风还没有准备好。请允许浏览器使用麦克风后，再试一次。');}}
  function complete(){record(s,episodeId,true);setResult({attempt_id:'',is_correct:true,message:'这句跟读已经收进今天的成长记录啦！'});}
  return <Surface className="practice-card"><p className="eyebrow"><Mic size={18}/> 句子跟读</p><h2 lang="en">{s.english}</h2><p className="prompt">{s.chinese}</p><div className="practice-actions"><Button variant="secondary" onClick={()=>speak(s.english)}><Volume2 size={20}/> 先听一遍</Button><Button onClick={()=>void toggle()}>{recording?<Pause size={20}/>:<Mic size={20}/>}{recording?'结束录音':'开始录音'}</Button></div>{message&&<p className="gentle-note" role="status">{message}</p>}{recordingUrl&&<div className="practice-recording"><p>这是你刚才的录音，听一听再完成这一句吧。</p><audio controls src={recordingUrl}>你的浏览器暂时不能播放录音。</audio></div>}<Button onClick={complete} disabled={!recordingUrl}>完成本句跟读</Button><ExerciseNavigator index={i} total={sentences.length} onChange={goTo}/>{result&&<ResultCard result={result} next={()=>goTo(i+1)} nextDisabled={i===sentences.length-1}/>}</Surface>;}
