import { createTextbookUnitPages } from './createTextbookUnitPages';

export const pepGrade4UpperUnit4Pages = createTextbookUnitPages('pep4a-u4', [
  { printedPage: 38, title: 'Helping in the community', chineseTitle: '在社区帮忙', focus: [{ english: 'community helper', chinese: '社区帮手', source: 'appendix-vocabulary' }, { english: 'How can we help our community?', chinese: '我们怎样帮助社区？', source: 'appendix-expression' }], lines: [{ english: 'How can we help our community?', chinese: '我们怎样帮助社区？', focus: ['How can we help our community?'] }, { english: 'Community helpers do important jobs.', chinese: '社区帮手做着重要的工作。', focus: ['community helper'] }] },
  { printedPage: 39, title: 'Look and think', chineseTitle: '看一看，想一想', focus: [{ english: 'cross the street', chinese: '过马路', source: 'appendix-expression' }, { english: 'old people', chinese: '老人', source: 'appendix-vocabulary' }], lines: [{ english: 'What jobs are important in a community?', chinese: '社区里哪些工作很重要？' }, { english: 'Some help others cross the street.', chinese: '有些人帮助别人过马路。', focus: ['cross the street'] }, { english: 'I can sing for old people.', chinese: '我可以为老人唱歌。', focus: ['old people'] }] },
  { printedPage: 40, title: 'What jobs are important?', chineseTitle: '哪些工作很重要？', focus: [{ english: 'firefighter', chinese: '消防员', source: 'appendix-word' }, { english: 'school bus driver', chinese: '校车司机', source: 'appendix-vocabulary' }, { english: 'cleaner', chinese: '清洁工', source: 'appendix-word' }], lines: [{ english: 'Our neighbour is a firefighter.', chinese: '我们的邻居是一位消防员。', focus: ['firefighter'] }, { english: 'He often helps people.', chinese: '他经常帮助别人。' }, { english: 'He is a school bus driver.', chinese: '他是一名校车司机。', focus: ['school bus driver'] }, { english: 'He is a cleaner. He cleans the community.', chinese: '他是一名清洁工。他打扫社区。', focus: ['cleaner'] }] },
  { printedPage: 41, title: 'Let’s learn', chineseTitle: '学一学：职业', focus: [{ english: 'delivery worker', chinese: '快递员', source: 'appendix-word' }, { english: 'cook', chinese: '厨师', source: 'appendix-word' }, { english: 'police officer', chinese: '警察', source: 'appendix-word' }], lines: [{ english: 'My neighbour is a police officer.', chinese: '我的邻居是一名警察。', focus: ['police officer'] }, { english: 'She helps a lot of people.', chinese: '她帮助很多人。' }, { english: 'A delivery worker brings things to people.', chinese: '快递员给人们送东西。', focus: ['delivery worker'] }, { english: 'A cook makes nice food.', chinese: '厨师做美味的食物。', focus: ['cook'] }] },
  { printedPage: 42, title: 'Let’s spell', chineseTitle: '拼读 ph', focus: [{ english: 'ph', chinese: '字母组合 ph', source: 'body' }, { english: 'phone', chinese: '电话', source: 'appendix-word' }, { english: 'photo', chinese: '照片', source: 'appendix-word' }], lines: [{ english: 'Philip has a phone.', chinese: '菲利普有一部电话。', focus: ['phone'] }, { english: 'He takes photos with his phone.', chinese: '他用电话拍照。', focus: ['photo', 'phone'] }, { english: 'elephant, Philip, phone, photo', chinese: '读一读含 ph 的单词。', focus: ['ph'] }] },
  { printedPage: 43, title: 'How can young people help?', chineseTitle: '年轻人怎样帮忙？', focus: [{ english: 'make the bed', chinese: '整理床铺', source: 'appendix-expression' }, { english: 'tell funny stories', chinese: '讲有趣的故事', source: 'appendix-expression' }, { english: 'sing old songs', chinese: '唱老歌', source: 'appendix-expression' }], lines: [{ english: 'Chen Jie is making the bed.', chinese: '陈洁正在整理床铺。', focus: ['make the bed'] }, { english: 'Binbin and John are telling funny stories.', chinese: '斌斌和约翰正在讲有趣的故事。', focus: ['tell funny stories'] }, { english: 'He is singing old songs.', chinese: '他正在唱老歌。', focus: ['sing old songs'] }] },
  { printedPage: 44, title: 'Let’s learn', chineseTitle: '学一学：正在做什么', focus: [{ english: 'clean the room', chinese: '打扫房间', source: 'appendix-expression' }, { english: 'be doing', chinese: '正在做……', source: 'appendix-vocabulary' }], lines: [{ english: 'She is making the bed.', chinese: '她正在整理床铺。' }, { english: 'They are cleaning the room.', chinese: '他们正在打扫房间。', focus: ['clean the room', 'be doing'] }, { english: 'A cook is cooking at the children’s centre.', chinese: '一名厨师正在儿童中心做饭。' }] },
  { printedPage: 45, title: 'Read and write', chineseTitle: '读一读，写一写', focus: [{ english: 'kindergarten', chinese: '幼儿园', source: 'appendix-word' }, { english: 'old people’s home', chinese: '养老院', source: 'appendix-vocabulary' }, { english: 'community helpers', chinese: '社区帮手', source: 'appendix-vocabulary' }], lines: [{ english: 'We are community helpers.', chinese: '我们是社区帮手。', focus: ['community helpers'] }, { english: 'John and Class One are singing songs together.', chinese: '约翰和一班正在一起唱歌。' }, { english: 'Chen Jie is making the bed in the old people’s home.', chinese: '陈洁正在养老院整理床铺。', focus: ['old people’s home'] }] },
  { printedPage: 46, title: 'Project: School helpers', chineseTitle: '项目：学校帮手', focus: [{ english: 'poster', chinese: '海报', source: 'appendix-word' }, { english: 'school helper', chinese: '学校帮手', source: 'appendix-vocabulary' }], lines: [{ english: 'Make a poster of your school helpers.', chinese: '制作一张学校帮手的海报。', focus: ['poster', 'school helper'] }, { english: 'A teacher helps students cross the road.', chinese: '一位老师帮助学生过马路。' }, { english: 'A cook is cooking our lunch.', chinese: '一名厨师正在做我们的午餐。' }] },
  { printedPage: 47, title: 'Share your poster', chineseTitle: '分享你的海报', focus: [{ english: 'important jobs', chinese: '重要的工作', source: 'appendix-vocabulary' }, { english: 'Self-check', chinese: '自我检查', source: 'body' }], lines: [{ english: 'Our school needs many helpers.', chinese: '我们的学校需要许多帮手。', focus: ['important jobs'] }, { english: 'He cleans our school.', chinese: '他打扫我们的学校。' }, { english: 'I can tell how people help in a community.', chinese: '我能说出人们怎样帮助社区。', focus: ['Self-check'] }] },
  { printedPage: 48, title: 'Reading time', chineseTitle: '阅读时间（一）', focus: [{ english: 'stay safe', chinese: '注意安全', source: 'appendix-expression' }, { english: 'red light', chinese: '红灯', source: 'appendix-vocabulary' }], lines: [{ english: 'Don’t swim there. It’s not safe.', chinese: '不要在那里游泳。那里不安全。', focus: ['stay safe'] }, { english: 'Don’t cross at a red light!', chinese: '红灯时不要过马路！', focus: ['red light'] }, { english: 'Stay safe in our community.', chinese: '在社区里注意安全。', focus: ['stay safe'] }] },
  { printedPage: 49, title: 'Reading time', chineseTitle: '阅读时间（二）', focus: [{ english: 'help each other', chinese: '互相帮助', source: 'appendix-expression' }, { english: 'be nice to', chinese: '对……友好', source: 'appendix-expression' }], lines: [{ english: 'We can all help old people.', chinese: '我们都可以帮助老人。' }, { english: 'We should help each other.', chinese: '我们应该互相帮助。', focus: ['help each other'] }, { english: 'Be nice to each other.', chinese: '要彼此友好。', focus: ['be nice to'] }] },
]);
