import { createTextbookUnitPages } from './createTextbookUnitPages';

export const pepGrade4UpperUnit5Pages = createTextbookUnitPages('pep4a-u5', [
  { printedPage: 50, title: 'The weather and us', chineseTitle: '天气和我们', focus: [{ english: 'weather', chinese: '天气', source: 'appendix-word' }, { english: 'How does the weather affect our lives?', chinese: '天气怎样影响我们的生活？', source: 'appendix-expression' }], lines: [{ english: 'How does the weather affect our lives?', chinese: '天气怎样影响我们的生活？', focus: ['How does the weather affect our lives?'] }, { english: 'Weather changes what we wear and do.', chinese: '天气会改变我们穿什么、做什么。', focus: ['weather'] }] },
  { printedPage: 51, title: 'Look and think', chineseTitle: '看一看，想一想', focus: [{ english: 'sunny', chinese: '晴朗的', source: 'appendix-word' }, { english: 'windy', chinese: '有风的', source: 'appendix-word' }, { english: 'snowy', chinese: '下雪的', source: 'appendix-word' }, { english: 'rainy', chinese: '下雨的', source: 'appendix-word' }], lines: [{ english: 'It’s sunny today. I do sports and play.', chinese: '今天晴朗。我做运动、玩耍。', focus: ['sunny'] }, { english: 'It’s windy today. I fly a kite and play.', chinese: '今天有风。我放风筝、玩耍。', focus: ['windy'] }, { english: 'It’s snowy today. I make a snowman.', chinese: '今天下雪。我堆雪人。', focus: ['snowy'] }, { english: 'It’s rainy today. I stay at home.', chinese: '今天下雨。我待在家里。', focus: ['rainy'] }] },
  { printedPage: 52, title: 'How can weather be different?', chineseTitle: '天气可以怎样不同？', focus: [{ english: 'degrees', chinese: '度', source: 'appendix-vocabulary' }, { english: 'What’s the weather like?', chinese: '天气怎么样？', source: 'appendix-expression' }, { english: 'cold', chinese: '寒冷的', source: 'appendix-word' }], lines: [{ english: 'What’s the weather like in Sydney?', chinese: '悉尼的天气怎么样？', focus: ['What’s the weather like?'] }, { english: 'It’s sunny today. It’s 21 degrees.', chinese: '今天晴朗。气温是21度。', focus: ['degrees'] }, { english: 'It’s cold in Beijing.', chinese: '北京很冷。', focus: ['cold'] }] },
  { printedPage: 53, title: 'Let’s learn', chineseTitle: '学一学：天气', focus: [{ english: 'cloudy', chinese: '多云的', source: 'appendix-word' }, { english: 'cool', chinese: '凉爽的', source: 'appendix-word' }, { english: 'warm', chinese: '温暖的', source: 'appendix-word' }, { english: 'hot', chinese: '炎热的', source: 'appendix-word' }], lines: [{ english: 'It’s cool and sunny.', chinese: '天气凉爽又晴朗。', focus: ['cool'] }, { english: 'It’s warm and windy.', chinese: '天气温暖又有风。', focus: ['warm'] }, { english: 'It’s cold and snowy.', chinese: '天气寒冷又下雪。' }, { english: 'It’s cloudy today.', chinese: '今天多云。', focus: ['cloudy'] }, { english: 'It’s hot today.', chinese: '今天很热。', focus: ['hot'] }] },
  { printedPage: 54, title: 'Let’s spell', chineseTitle: '拼读 th', focus: [{ english: 'th', chinese: '字母组合 th', source: 'body' }, { english: 'thank', chinese: '谢谢', source: 'appendix-word' }, { english: 'three', chinese: '三', source: 'appendix-word' }], lines: [{ english: 'I’m thirsty and hungry.', chinese: '我又渴又饿。' }, { english: 'These gifts are for you. Thanks.', chinese: '这些礼物是给你的。谢谢。', focus: ['thank'] }, { english: 'thank, these, there, them, think, they, three, thin', chinese: '读一读含 th 的单词。', focus: ['th', 'three'] }] },
  { printedPage: 55, title: 'What do we do in different weather?', chineseTitle: '不同天气做什么？', focus: [{ english: 'see a film', chinese: '看电影', source: 'appendix-expression' }, { english: 'can’t', chinese: '不能', source: 'appendix-vocabulary' }, { english: 'library', chinese: '图书馆', source: 'appendix-word' }], lines: [{ english: 'We can’t play basketball in the park.', chinese: '我们不能在公园打篮球。', focus: ['can’t'] }, { english: 'Let’s go and see a film.', chinese: '我们去看电影吧。', focus: ['see a film'] }, { english: 'We can go to the library.', chinese: '我们可以去图书馆。', focus: ['library'] }] },
  { printedPage: 56, title: 'Let’s learn', chineseTitle: '学一学：天气活动', focus: [{ english: 'play basketball', chinese: '打篮球', source: 'appendix-expression' }, { english: 'fly a kite', chinese: '放风筝', source: 'appendix-expression' }, { english: 'make a snowman', chinese: '堆雪人', source: 'appendix-expression' }], lines: [{ english: 'On sunny days, we can play basketball.', chinese: '晴天我们可以打篮球。', focus: ['play basketball'] }, { english: 'On snowy days, we can make a snowman.', chinese: '下雪天我们可以堆雪人。', focus: ['make a snowman'] }, { english: 'We can fly a kite on windy days.', chinese: '有风天我们可以放风筝。', focus: ['fly a kite'] }] },
  { printedPage: 57, title: 'Read and write', chineseTitle: '读一读，写一写', focus: [{ english: 'postcard', chinese: '明信片', source: 'appendix-word' }, { english: 'pool', chinese: '游泳池', source: 'appendix-word' }], lines: [{ english: 'I’m in a big park in Sydney today.', chinese: '今天我在悉尼的一个大公园里。', focus: ['postcard'] }, { english: 'It’s hot and sunny here.', chinese: '这里天气炎热又晴朗。' }, { english: 'We play basketball together.', chinese: '我们一起打篮球。' }, { english: 'Their children swim in the pool.', chinese: '他们的孩子在游泳池里游泳。', focus: ['pool'] }] },
  { printedPage: 58, title: 'Project: Bad weather reminder', chineseTitle: '项目：恶劣天气提醒', focus: [{ english: 'heavy rain', chinese: '大雨', source: 'appendix-vocabulary' }, { english: 'strong wind', chinese: '强风', source: 'appendix-vocabulary' }], lines: [{ english: 'It’s cool and cloudy. We can play basketball.', chinese: '天气凉爽多云。我们可以打篮球。' }, { english: 'There is heavy rain now. We can’t play basketball.', chinese: '现在有大雨。我们不能打篮球。', focus: ['heavy rain'] }, { english: 'There is a strong wind.', chinese: '有强风。', focus: ['strong wind'] }] },
  { printedPage: 59, title: 'Make your reminder', chineseTitle: '制作你的提醒', focus: [{ english: 'outside', chinese: '在户外', source: 'appendix-vocabulary' }, { english: 'Self-check', chinese: '自我检查', source: 'body' }], lines: [{ english: 'It’s too hot. We can’t play football outside.', chinese: '太热了。我们不能在户外踢足球。', focus: ['outside'] }, { english: 'I can talk about different weather.', chinese: '我能谈论不同的天气。', focus: ['Self-check'] }, { english: 'I can say what we do in different weather.', chinese: '我能说出不同天气做什么。' }] },
  { printedPage: 60, title: 'Reading time', chineseTitle: '阅读时间（一）', focus: [{ english: 'grass', chinese: '草地', source: 'appendix-word' }, { english: 'have fun', chinese: '玩得开心', source: 'appendix-expression' }], lines: [{ english: 'It’s sunny. They’re playing football on the grass.', chinese: '天晴了。他们正在草地上踢足球。', focus: ['grass'] }, { english: 'It’s windy. The boy is flying a kite.', chinese: '有风。男孩正在放风筝。' }, { english: 'He’s having fun.', chinese: '他玩得很开心。', focus: ['have fun'] }] },
  { printedPage: 61, title: 'Reading time', chineseTitle: '阅读时间（二）', focus: [{ english: 'raincoat', chinese: '雨衣', source: 'appendix-word' }, { english: 'boots', chinese: '靴子', source: 'appendix-word' }], lines: [{ english: 'It’s snowy. They’re making a snowman.', chinese: '下雪了。他们正在堆雪人。' }, { english: 'It’s rainy and cool. We can wear raincoats and boots.', chinese: '下雨又凉爽。我们可以穿雨衣和靴子。', focus: ['raincoat', 'boots'] }, { english: 'Let’s go out and dance in the rain.', chinese: '我们出去在雨中跳舞吧。' }] },
]);
