import { createTextbookUnitPages } from './createTextbookUnitPages';

export const pepGrade4UpperUnit6Pages = createTextbookUnitPages('pep4a-u6', [
  { printedPage: 62, title: 'Changing for the seasons', chineseTitle: '随季节变化', focus: [{ english: 'season', chinese: '季节', source: 'appendix-word' }, { english: 'How are our lives different in each season?', chinese: '每个季节我们的生活有什么不同？', source: 'appendix-expression' }], lines: [{ english: 'How are our lives different in each season?', chinese: '每个季节我们的生活有什么不同？', focus: ['How are our lives different in each season?'] }, { english: 'Seasons change our clothes and activities.', chinese: '季节会改变我们的衣服和活动。', focus: ['season'] }] },
  { printedPage: 63, title: 'Look and think', chineseTitle: '看一看，想一想', focus: [{ english: 'spring', chinese: '春天', source: 'appendix-word' }, { english: 'summer', chinese: '夏天', source: 'appendix-word' }, { english: 'autumn', chinese: '秋天', source: 'appendix-word' }, { english: 'winter', chinese: '冬天', source: 'appendix-word' }], lines: [{ english: 'Spring, summer, autumn and winter.', chinese: '春天、夏天、秋天和冬天。', focus: ['spring', 'summer', 'autumn', 'winter'] }, { english: 'In spring, wear a sweater.', chinese: '春天穿毛衣。' }, { english: 'In summer, wear shorts.', chinese: '夏天穿短裤。' }, { english: 'In winter, wear a lot!', chinese: '冬天要多穿些！' }] },
  { printedPage: 64, title: 'What do we wear in different seasons?', chineseTitle: '不同季节穿什么？', focus: [{ english: 'whose', chinese: '谁的', source: 'appendix-word' }, { english: 'coat', chinese: '外套', source: 'appendix-word' }, { english: 'sweater', chinese: '毛衣', source: 'appendix-word' }], lines: [{ english: 'Whose sweater is this?', chinese: '这是谁的毛衣？', focus: ['whose', 'sweater'] }, { english: 'It’s your dad’s.', chinese: '它是你爸爸的。' }, { english: 'Wear a coat too. It’s cold and windy outside.', chinese: '也穿一件外套。外面又冷又有风。', focus: ['coat'] }] },
  { printedPage: 65, title: 'Let’s learn', chineseTitle: '学一学：衣物', focus: [{ english: 'dress', chinese: '连衣裙', source: 'appendix-word' }, { english: 'socks', chinese: '袜子', source: 'appendix-word' }, { english: 'shirt', chinese: '衬衫', source: 'appendix-word' }], lines: [{ english: 'This purple dress is Mum’s.', chinese: '这条紫色连衣裙是妈妈的。', focus: ['dress'] }, { english: 'The pink socks are mine.', chinese: '这双粉色袜子是我的。', focus: ['socks'] }, { english: 'The blue shirt is his.', chinese: '这件蓝衬衫是他的。', focus: ['shirt'] }] },
  { printedPage: 66, title: 'Let’s spell', chineseTitle: '拼读 wh', focus: [{ english: 'wh', chinese: '字母组合 wh', source: 'body' }, { english: 'where', chinese: '哪里', source: 'appendix-word' }, { english: 'why', chinese: '为什么', source: 'appendix-word' }], lines: [{ english: 'Why is winter so cold?', chinese: '为什么冬天这么冷？', focus: ['why'] }, { english: 'What do you wear in the snow?', chinese: '下雪时你穿什么？' }, { english: 'Where is my glove?', chinese: '我的手套在哪里？', focus: ['where'] }, { english: 'where, who, white, why, what, which, whose', chinese: '读一读含 wh 的单词。', focus: ['wh'] }] },
  { printedPage: 67, title: 'What do we do in different seasons?', chineseTitle: '不同季节做什么？', focus: [{ english: 'Which season do you like?', chinese: '你喜欢哪个季节？', source: 'appendix-expression' }, { english: 'get together', chinese: '聚在一起', source: 'appendix-expression' }], lines: [{ english: 'Which season do you like?', chinese: '你喜欢哪个季节？', focus: ['Which season do you like?'] }, { english: 'Winter. I can play in the snow and make a snowman.', chinese: '冬天。我可以在雪里玩、堆雪人。' }, { english: 'My family and I often get together and have fun.', chinese: '我的家人和我常常聚在一起，玩得很开心。', focus: ['get together'] }] },
  { printedPage: 68, title: 'Let’s learn', chineseTitle: '学一学：四季', focus: [{ english: 'make a snowman', chinese: '堆雪人', source: 'appendix-expression' }, { english: 'favourite season', chinese: '最喜欢的季节', source: 'appendix-vocabulary' }], lines: [{ english: 'Which season do you like?', chinese: '你喜欢哪个季节？', focus: ['favourite season'] }, { english: 'Winter. I can make a snowman.', chinese: '冬天。我可以堆雪人。', focus: ['make a snowman'] }, { english: 'Thirty students like spring.', chinese: '三十名学生喜欢春天。' }] },
  { printedPage: 69, title: 'Read and write', chineseTitle: '读一读，写一写', focus: [{ english: 'falling leaves', chinese: '落叶', source: 'appendix-vocabulary' }, { english: 'gloves', chinese: '手套', source: 'appendix-word' }, { english: 'moon cakes', chinese: '月饼', source: 'appendix-word' }], lines: [{ english: 'Spring is green. It’s full of life.', chinese: '春天是绿色的。它充满生机。' }, { english: 'I like the falling leaves.', chinese: '我喜欢落叶。', focus: ['falling leaves'] }, { english: 'I wear warm coats and gloves.', chinese: '我穿暖和的外套和手套。', focus: ['gloves'] }, { english: 'I enjoy moon cakes.', chinese: '我喜欢吃月饼。', focus: ['moon cakes'] }] },
  { printedPage: 70, title: 'Project: Make a travel card', chineseTitle: '项目：制作旅行卡', focus: [{ english: 'travel card', chinese: '旅行卡', source: 'appendix-vocabulary' }, { english: 'cap', chinese: '帽子', source: 'appendix-word' }], lines: [{ english: 'Make a travel card.', chinese: '制作一张旅行卡。', focus: ['travel card'] }, { english: 'The green sweater is Mike’s.', chinese: '这件绿色毛衣是迈克的。' }, { english: 'Choose a cap, coat, dress, shirt, socks or sweater.', chinese: '选择一件帽子、外套、连衣裙、衬衫、袜子或毛衣。', focus: ['cap'] }] },
  { printedPage: 71, title: 'Share your travel card', chineseTitle: '分享你的旅行卡', focus: [{ english: 'seafood', chinese: '海鲜', source: 'appendix-word' }, { english: 'Self-check', chinese: '自我检查', source: 'body' }], lines: [{ english: 'I like spring. It’s warm and windy.', chinese: '我喜欢春天。天气温暖又有风。' }, { english: 'I can go to the park and fly kites.', chinese: '我可以去公园放风筝。' }, { english: 'I can eat seafood.', chinese: '我可以吃海鲜。', focus: ['seafood'] }, { english: 'I can talk about my favourite season.', chinese: '我能谈论我最喜欢的季节。', focus: ['Self-check'] }] },
  { printedPage: 72, title: 'Reading time', chineseTitle: '阅读时间（一）', focus: [{ english: 'Christmas Day', chinese: '圣诞节', source: 'appendix-vocabulary' }, { english: 'beach', chinese: '海滩', source: 'appendix-word' }], lines: [{ english: 'Merry Christmas!', chinese: '圣诞快乐！', focus: ['Christmas Day'] }, { english: 'I put on my shorts and T-shirt and go to the beach.', chinese: '我穿上短裤和T恤，去海滩。', focus: ['beach'] }, { english: 'It’s cool at night. I need to wear a sweater.', chinese: '晚上很凉。我需要穿一件毛衣。' }] },
  { printedPage: 73, title: 'Reading time', chineseTitle: '阅读时间（二）', focus: [{ english: 'warm hat', chinese: '暖和的帽子', source: 'appendix-vocabulary' }, { english: 'snowman', chinese: '雪人', source: 'appendix-word' }], lines: [{ english: 'It’s cold and snowy. You need a warm hat.', chinese: '天气又冷又下雪。你需要一顶暖和的帽子。', focus: ['warm hat'] }, { english: 'It’s a snowman.', chinese: '它是一个雪人。', focus: ['snowman'] }, { english: 'Snowmen love cold weather.', chinese: '雪人喜欢寒冷的天气。' }] },
]);
