import { createTextbookUnitPages } from './createTextbookUnitPages';

export const pepGrade4UpperUnit3Pages = createTextbookUnitPages('pep4a-u3', [
  { printedPage: 26, title: 'Places we live in', chineseTitle: '我们生活的地方', focus: [{ english: 'community', chinese: '社区', source: 'appendix-word' }, { english: 'What makes a community?', chinese: '是什么构成了一个社区？', source: 'appendix-expression' }], lines: [{ english: 'What makes a community?', chinese: '是什么构成了一个社区？', focus: ['What makes a community?'] }, { english: 'A community is a place for us all.', chinese: '社区是属于我们大家的地方。', focus: ['community'] }] },
  { printedPage: 27, title: 'Look and think', chineseTitle: '看一看，想一想', focus: [{ english: 'park', chinese: '公园', source: 'appendix-word' }, { english: 'hospital', chinese: '医院', source: 'appendix-word' }], lines: [{ english: 'What is this place?', chinese: '这是什么地方？' }, { english: 'The park or the hospital?', chinese: '是公园还是医院？', focus: ['park', 'hospital'] }, { english: 'We all make our community!', chinese: '我们共同构成社区！' }] },
  { printedPage: 28, title: 'What can we see in a community?', chineseTitle: '社区里有什么？', focus: [{ english: 'neighbour', chinese: '邻居', source: 'appendix-word' }, { english: 'playground', chinese: '操场；游乐场', source: 'appendix-word' }, { english: 'There is ...', chinese: '有……', source: 'appendix-expression' }], lines: [{ english: 'Your neighbours are very friendly.', chinese: '你的邻居非常友好。', focus: ['neighbour'] }, { english: 'There is a playground. We often play there.', chinese: '有一个游乐场。我们常在那里玩。', focus: ['playground', 'There is ...'] }, { english: 'There is also a nice park over there.', chinese: '那边还有一个漂亮的公园。' }] },
  { printedPage: 29, title: 'Let’s learn', chineseTitle: '学一学：社区场所', focus: [{ english: 'shop', chinese: '商店', source: 'appendix-word' }, { english: 'bus stop', chinese: '公交车站', source: 'appendix-word' }, { english: 'toilets', chinese: '洗手间', source: 'appendix-word' }], lines: [{ english: 'We’re at the park.', chinese: '我们在公园。' }, { english: 'Look! There is a shop.', chinese: '看！有一家商店。', focus: ['shop'] }, { english: 'There is also a playground.', chinese: '还有一个游乐场。' }, { english: 'Where is the bus stop?', chinese: '公交车站在哪里？', focus: ['bus stop'] }] },
  { printedPage: 30, title: 'Let’s spell', chineseTitle: '拼读 ck', focus: [{ english: 'ck', chinese: '字母组合 ck', source: 'body' }, { english: 'duck', chinese: '鸭子', source: 'appendix-word' }, { english: 'black', chinese: '黑色的', source: 'appendix-word' }], lines: [{ english: 'Some ducks are in the park.', chinese: '一些鸭子在公园里。', focus: ['duck'] }, { english: 'The poor ducklings feel cold there.', chinese: '可怜的小鸭子在那里觉得冷。' }, { english: 'black, sock, back, duck, tick', chinese: '读一读含 ck 的单词。', focus: ['ck', 'black', 'duck'] }] },
  { printedPage: 31, title: 'What do people do in a community?', chineseTitle: '人们在社区做什么？', focus: [{ english: 'library', chinese: '图书馆', source: 'appendix-word' }, { english: 'gym', chinese: '健身房', source: 'appendix-word' }, { english: 'There are ...', chinese: '有……（复数）', source: 'appendix-expression' }], lines: [{ english: 'This is a library.', chinese: '这是一家图书馆。', focus: ['library'] }, { english: 'There are so many books.', chinese: '有这么多书。', focus: ['There are ...'] }, { english: 'There is a gym too.', chinese: '还有一个健身房。', focus: ['gym'] }] },
  { printedPage: 32, title: 'Let’s learn', chineseTitle: '学一学：社区活动', focus: [{ english: 'go shopping', chinese: '购物', source: 'appendix-expression' }, { english: 'take a walk', chinese: '散步', source: 'appendix-expression' }, { english: 'do sports', chinese: '做运动', source: 'appendix-expression' }, { english: 'see a doctor', chinese: '看医生', source: 'appendix-expression' }], lines: [{ english: 'I often do sports there.', chinese: '我经常在那里做运动。', focus: ['do sports'] }, { english: 'I often take a walk there.', chinese: '我经常在那里散步。', focus: ['take a walk'] }, { english: 'I go shopping there.', chinese: '我在那里购物。', focus: ['go shopping'] }, { english: 'I see a doctor there.', chinese: '我在那里看医生。', focus: ['see a doctor'] }] },
  { printedPage: 33, title: 'Read and write', chineseTitle: '读一读，写一写', focus: [{ english: 'museum', chinese: '博物馆', source: 'appendix-word' }, { english: 'favourite place', chinese: '最喜欢的地方', source: 'appendix-vocabulary' }, { english: 'gifts', chinese: '礼物', source: 'appendix-word' }], lines: [{ english: 'My favourite place is the museum.', chinese: '我最喜欢的地方是博物馆。', focus: ['museum', 'favourite place'] }, { english: 'There are many old things and photos.', chinese: '有许多旧物品和照片。' }, { english: 'People buy gifts and books there.', chinese: '人们在那里买礼物和书。', focus: ['gifts'] }] },
  { printedPage: 34, title: 'Project: Dream community', chineseTitle: '项目：梦想社区', focus: [{ english: 'dream community', chinese: '梦想社区', source: 'appendix-vocabulary' }, { english: 'have fun', chinese: '玩得开心', source: 'appendix-expression' }], lines: [{ english: 'What is in your dream community?', chinese: '你的梦想社区里有什么？', focus: ['dream community'] }, { english: 'There is a shop in our dream community.', chinese: '我们的梦想社区里有一家商店。' }, { english: 'Children can have fun there.', chinese: '孩子们可以在那里玩得开心。', focus: ['have fun'] }] },
  { printedPage: 35, title: 'Present your community', chineseTitle: '展示你的社区', focus: [{ english: 'People often ...', chinese: '人们常常……', source: 'appendix-expression' }, { english: 'Self-check', chinese: '自我检查', source: 'body' }], lines: [{ english: 'This is my dream community.', chinese: '这是我的梦想社区。' }, { english: 'There is ... People often ...', chinese: '有……人们常常……', focus: ['People often ...'] }, { english: 'I can tell people about places in my community.', chinese: '我能告诉大家社区里的场所。', focus: ['Self-check'] }] },
  { printedPage: 36, title: 'Reading time', chineseTitle: '阅读时间（一）', focus: [{ english: 'video diary', chinese: '视频日记', source: 'appendix-vocabulary' }, { english: 'Nice to meet you!', chinese: '很高兴认识你！', source: 'appendix-expression' }], lines: [{ english: 'This is my video diary.', chinese: '这是我的视频日记。', focus: ['video diary'] }, { english: 'Nice to meet you!', chinese: '很高兴认识你！', focus: ['Nice to meet you!'] }, { english: 'Would you like some vegetables?', chinese: '你想吃一些蔬菜吗？' }] },
  { printedPage: 37, title: 'Reading time', chineseTitle: '阅读时间（二）', focus: [{ english: 'panda', chinese: '熊猫', source: 'appendix-word' }, { english: 'I love Chengdu!', chinese: '我爱成都！', source: 'appendix-expression' }], lines: [{ english: 'Do you like pandas?', chinese: '你喜欢熊猫吗？', focus: ['panda'] }, { english: 'There are nice people and great places here.', chinese: '这里有很好的人和很棒的地方。' }, { english: 'I love Chengdu!', chinese: '我爱成都！', focus: ['I love Chengdu!'] }] },
]);
